require('setup.settings')

require('setup.nvimtree')
require('setup.nvimtreesitter')
require('setup.theme')
require('setup.indentblankline')
require('setup.plugins')
require('setup.lspkind')
require('setup.fzf')
require('setup.lightline')
require('setup.fine-cmdline')

require('mappings.fzf')
require('mappings.general')
require('mappings.movement')
require('mappings.nvimtree')
require('mappings.vimtest')
